version: '3.8'

services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - DB_URL=mongodb://api_mongodb:27017
            - REDIS_TYPE=single
            - REDIS_INITIAL_NODE_URL=redis://api_session_redis:6379
        networks:
            - base
            - api

    api_mongodb:
        container_name: api_mongodb
        build:
            context: .
            dockerfile: mongodb/single/Dockerfile
            target: development
        ports:
                - 8082:27017
        environment:
            username: admin
            password: password
            databaseName: primaryDB
        networks:
            - api

    api_session_redis:
        container_name: api_session_redis
        image: redis:7.0
        ports:
            - 6379:6379
        networks:
            - api

    authorization:
        container_name: authorization
        build: 
            context: ../Authorization
            dockerfile: Dockerfile
            target: development
        ports:
            - 3001:3000
        volumes:
            - ../Authorization:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - REDIS_TYPE=single
            - REDIS_INITIAL_NODE_URL=redis://authorization_session_redis:6379
            - DB_SUPPORTS_TRANSACTION=false
            - DB_URL=mongodb://authorization_mongodb:27017
        networks:
            - authorization
            - base

    authorization_mongodb:
        container_name: authorization_mongodb
        build:
            context: ../Authorization
            dockerfile: ./mongodb/single/Dockerfile
            target: development
        ports:
                - 8083:27017
        environment:
            username: admin
            password: password
            databaseName: primaryDB
        networks:
            - authorization

    authorization_session_redis:
        container_name: authorization_session_redis
        image: redis:7.0
        ports:
            - 6379:6379
        networks:
            - authorization

    # authorization_revoked_tokens_redis:
    #     container_name: authorization_revoked_tokens_redis
    #     image: redis:7.0
    #     ports:
    #         - 6379:6379
    #     networks:
    #         - authorization

networks:
    base:
    api:
    authorization:
