version: '3.8'

services:
  redis-1:
    image: redis-cluster
    environment:
      - REDIS_CLUSTER_INIT=true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "7000:6379"
    volumes:
      - redis-data-1:/data
    networks:
      - redis-cluster

  redis-2:
    image: redis-cluster
    environment:
      - REDIS_CLUSTER_INIT=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "7001:6379"
    volumes:
      - redis-data-2:/data
    networks:
      - redis-cluster

  redis-3:
    image: redis-cluster
    environment:
      - REDIS_CLUSTER_INIT=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "7002:6379"
    volumes:
      - redis-data-3:/data
    networks:
      - redis-cluster

  redis-4:
    image: redis-cluster
    environment:
      - REDIS_CLUSTER_INIT=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    ports:
      - "7003:6379"
    volumes:
      - redis-data-4:/data
    networks:
      - redis-cluster

  redis-5:
    image: redis-cluster
    environment:
      - REDIS_CLUSTER_INIT=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    ports:
      - "7004:6379"
    volumes:
      - redis-data-5:/data
    networks:
      - redis-cluster

  redis-6:
    image: redis-cluster
    environment:
      - REDIS_CLUSTER_INIT=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    ports:
      - "7005:6379"
    volumes:
      - redis-data-6:/data
    networks:
      - redis-cluster

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-data-5:
  redis-data-6:

networks:
  redis-cluster:
    driver: overlay
