version: '3.8'

services:
    ############################################################################################# mongo_express
    mongo_express:
        container_name: mongo_express
        image: mongo-express:latest
        restart: always
        environment:
            - ME_CONFIG_MONGODB_SERVER=main_mongodb_mongos1
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=password
        ports:
            - 8081:8081
        depends_on:
            - main_mongodb_mongos1
        networks:
            - base

    ############################################################################################# redis_commander
    redis_commander:
        container_name: redis_commander
        hostname: redis_commander
        user: redis
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=cluster1:revoked_access_tokens_redis_1:6379,cluster2:api_redis_1:6379,cluster3:authorization_redis_1:6379
        ports:
            - 8082:8081
        depends_on:
            - revoked_access_tokens_redis_1
            - api_redis_1
            - authorization_redis_1
        networks:
            - base
            - api_redis
            - authorization_redis

    ############################################################################################# main_mongodb
    # Initialization Service
    main_mongodb_init:
        image: mongo:4.0
        container_name: main_mongodb_init
        entrypoint: ["sh", "-c", "sleep 40s && chmod +x /scripts/init.sh && /scripts/init.sh"]
        volumes:
            - ./mongodb/sharded/scripts:/scripts
        depends_on:
            - main_mongodb_config1
            - main_mongodb_config2
            - main_mongodb_config3
            - main_mongodb_shard1a
            - main_mongodb_shard1b
            - main_mongodb_shard1c
            - main_mongodb_shard2a
            - main_mongodb_shard2b
            - main_mongodb_shard2c
            - main_mongodb_mongos1
            - main_mongodb_mongos2
        environment:
            MONGODB_USERNAME: admin
            MONGODB_PASSWORD: password
        networks:
            - main_mongodb

    # Mongos Routers (2 instances for high availability)
    main_mongodb_mongos1:
        image: mongo:4.0
        container_name: main_mongodb_mongos1
        entrypoint: ["sh", "-c", "sleep 20s && mongos --port 27017 --configdb configrs/main_mongodb_config1:27017,main_mongodb_config2:27017,main_mongodb_config3:27017 --bind_ip_all"]
        ports:
            - "27017:27017"
        depends_on:
            - main_mongodb_config1
            - main_mongodb_config2
            - main_mongodb_config3
            - main_mongodb_shard1a
            - main_mongodb_shard1b
            - main_mongodb_shard1c
            - main_mongodb_shard2a
            - main_mongodb_shard2b
            - main_mongodb_shard2c
        environment:
            USERNAME: admin
            PASSWORD: password
        networks:
            - base
            - main_mongodb

    main_mongodb_mongos2:
        image: mongo:4.0
        container_name: main_mongodb_mongos2
        entrypoint: ["sh", "-c", "sleep 20s && mongos --port 27017 --configdb configrs/main_mongodb_config1:27017,main_mongodb_config2:27017,main_mongodb_config3:27017 --bind_ip_all"]
        ports:
            - "27018:27017"
        depends_on:
            - main_mongodb_config1
            - main_mongodb_config2
            - main_mongodb_config3
            - main_mongodb_shard1a
            - main_mongodb_shard1b
            - main_mongodb_shard1c
            - main_mongodb_shard2a
            - main_mongodb_shard2b
            - main_mongodb_shard2c
        networks:
            - base
            - main_mongodb

    # Config Servers (3-node replica set)
    main_mongodb_config1:
        image: mongo:4.0
        container_name: main_mongodb_config1
        command: mongod --port 27017 --configsvr --replSet configrs --bind_ip_all
        networks:
            - main_mongodb

    main_mongodb_config2:
        image: mongo:4.0
        container_name: main_mongodb_config2
        command: mongod --port 27017 --configsvr --replSet configrs --bind_ip_all
        networks:
            - main_mongodb

    main_mongodb_config3:
        image: mongo:4.0
        container_name: main_mongodb_config3
        command: mongod --port 27017 --configsvr --replSet configrs --bind_ip_all
        networks:
            - main_mongodb

    # Shard Servers (2 shards, each a 3-node replica set)
    main_mongodb_shard1a:
        image: mongo:4.0
        container_name: main_mongodb_shard1a
        command: mongod --port 27017 --shardsvr --replSet shard1rs --bind_ip_all
        networks:
            - main_mongodb

    main_mongodb_shard1b:
        image: mongo:4.0
        container_name: main_mongodb_shard1b
        command: mongod --port 27017 --shardsvr --replSet shard1rs --bind_ip_all
        networks:
            - main_mongodb

    main_mongodb_shard1c:
        image: mongo:4.0
        container_name: main_mongodb_shard1c
        command: mongod --port 27017 --shardsvr --replSet shard1rs --bind_ip_all
        networks:
            - main_mongodb

    main_mongodb_shard2a:
        image: mongo:4.0
        container_name: main_mongodb_shard2a
        command: mongod --port 27017 --shardsvr --replSet shard2rs --bind_ip_all
        networks:
            - main_mongodb

    main_mongodb_shard2b:
        image: mongo:4.0
        container_name: main_mongodb_shard2b
        command: mongod --port 27017 --shardsvr --replSet shard2rs --bind_ip_all
        networks:
            - main_mongodb

    main_mongodb_shard2c:
        image: mongo:4.0
        container_name: main_mongodb_shard2c
        command: mongod --port 27017 --shardsvr --replSet shard2rs --bind_ip_all
        networks:
            - main_mongodb

    ############################################################################################# revoked_access_tokens_redis
    revoked_access_tokens_redis_1:
        container_name: revoked_access_tokens_redis_1
        build:
            context: .
            dockerfile: ./revoked_access_tokens_redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=revoked_access_tokens_redis_1
            - REDIS_CLUSTER_INIT=true
            - nodes=revoked_access_tokens_redis_1:6379 revoked_access_tokens_redis_2:6379 revoked_access_tokens_redis_3:6379 revoked_access_tokens_redis_4:6379 revoked_access_tokens_redis_5:6379 revoked_access_tokens_redis_6:6379
        ports:
            - 7000:6379
        networks:
            - base
            - revoked_access_tokens_redis

    revoked_access_tokens_redis_2:
        container_name: revoked_access_tokens_redis_2
        build:
            context: .
            dockerfile: ./revoked_access_tokens_redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=revoked_access_tokens_redis_2
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7001:6379
        networks:
            - base
            - revoked_access_tokens_redis

    revoked_access_tokens_redis_3:
        container_name: revoked_access_tokens_redis_3
        build:
            context: .
            dockerfile: ./revoked_access_tokens_redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=revoked_access_tokens_redis_3
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7002:6379
        networks:
            - base
            - revoked_access_tokens_redis

    revoked_access_tokens_redis_4:
        container_name: revoked_access_tokens_redis_4
        build:
            context: .
            dockerfile: ./revoked_access_tokens_redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=revoked_access_tokens_redis_4
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7003:6379
        networks:
            - base
            - revoked_access_tokens_redis

    revoked_access_tokens_redis_5:
        container_name: revoked_access_tokens_redis_5
        build:
            context: .
            dockerfile: ./revoked_access_tokens_redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=revoked_access_tokens_redis_5
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7004:6379
        networks:
            - base
            - revoked_access_tokens_redis

    revoked_access_tokens_redis_6:
        container_name: revoked_access_tokens_redis_6
        build:
            context: .
            dockerfile: ./revoked_access_tokens_redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=revoked_access_tokens_redis_6
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7005:6379
        networks:
            - base
            - revoked_access_tokens_redis

    ############################################################################################# rabbitmq
    rabbitmq1:
        image: rabbitmq:3-management
        container_name: rabbitmq1
        hostname: rabbitmq1
        entrypoint: /entrypoint.sh
        ports:
            - "5672:5672"  # AMQP port for node 1
            - "15672:15672" # Management UI port for node 1
        environment:
            RABBITMQ_MANAGEMENT_DISABLE_METRICS_COLLECTOR: 'true'
            RABBITMQ_ERLANG_COOKIE: "secret_cookie" # Cluster cookie (must be the same for all nodes)
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: password
        volumes:
            - ./rabbitmq/cluster/init.sh:/entrypoint.sh # Mount the entrypoint script
        networks:
            - base
            - rabbitmq_cluster

    rabbitmq2:
        image: rabbitmq:3-management
        container_name: rabbitmq2
        hostname: rabbitmq2
        entrypoint: /entrypoint.sh
        ports:
            - "5673:5672"  # AMQP port for node 2
            - "15673:15672" # Management UI port for node 2
        environment:
            RABBITMQ_MANAGEMENT_DISABLE_METRICS_COLLECTOR: 'true'
            RABBITMQ_ERLANG_COOKIE: "secret_cookie" # Cluster cookie (must be the same for all nodes)
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: password
            CLUSTER_JOIN: rabbitmq1
        volumes:
            - ./rabbitmq/cluster/init.sh:/entrypoint.sh # Mount the entrypoint script
        networks:
            - base
            - rabbitmq_cluster
        depends_on:
            - rabbitmq1

    rabbitmq3:
        image: rabbitmq:3-management
        container_name: rabbitmq3
        hostname: rabbitmq3
        entrypoint: /entrypoint.sh
        ports:
            - "5674:5672"  # AMQP port for node 3
            - "15674:15672" # Management UI port for node 3
        environment:
            RABBITMQ_MANAGEMENT_DISABLE_METRICS_COLLECTOR: 'true'
            RABBITMQ_ERLANG_COOKIE: "secret_cookie" # Cluster cookie (must be the same for all nodes)
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: password
            CLUSTER_JOIN: rabbitmq1
        volumes:
            - ./rabbitmq/cluster/init.sh:/entrypoint.sh # Mount the entrypoint script
        networks:
            - base
            - rabbitmq_cluster
        depends_on:
            - rabbitmq2

    ############################################################################################# api
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - DB_SUPPORTS_TRANSACTION=true
            - DB_URL=mongodb://main_mongodb:27017
            - SESSION_REDIS_TYPE=cluster
            - SESSION_REDIS_INITIAL_NODE_URL=redis://api_redis_1:6379
            - REVOKED_TOKENS_REDIS_TYPE=cluster
            - REVOKED_TOKENS_REDIS_INITIAL_NODE_URL=redis://revoked_access_tokens_redis_1:6379
            - MESSAGE_BROKER_TYPE=cluster
            - MESSAGE_BROKER_MANAGEMENT_API_URL=rabbitmq1:15672
            - MESSAGE_BROKER_USERNAME=admin
            - MESSAGE_BROKER_PASSWORD=password
        networks:
            - base
            - api
            - api_redis

    ############################################################################################# api_redis
    api_redis_1:
        container_name: api_redis_1
        build:
            context: .
            dockerfile: ./redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=api_redis_1
            - REDIS_CLUSTER_INIT=true
            - nodes=api_redis_1:6379 api_redis_2:6379 api_redis_3:6379 api_redis_4:6379 api_redis_5:6379 api_redis_6:6379
        ports:
            - 7000:6379
        networks:
            - api_redis

    api_redis_2:
        container_name: api_redis_2
        build:
            context: .
            dockerfile: ./redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=api_redis_2
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7001:6379
        networks:
            - api_redis

    api_redis_3:
        container_name: api_redis_3
        build:
            context: .
            dockerfile: ./redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=api_redis_3
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7002:6379
        networks:
            - api_redis

    api_redis_4:
        container_name: api_redis_4
        build:
            context: .
            dockerfile: ./redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=api_redis_4
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7003:6379
        networks:
            - api_redis

    api_redis_5:
        container_name: api_redis_5
        build:
            context: .
            dockerfile: ./redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=api_redis_5
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7004:6379
        networks:
            - api_redis

    api_redis_6:
        container_name: api_redis_6
        build:
            context: .
            dockerfile: ./redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=api_redis_6
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7005:6379
        networks:
            - api_redis

    ############################################################################################# authorization
    authorization:
        container_name: authorization
        build: 
            context: ../Authorizatoin
            dockerfile: ../Authorizatoin/Dockerfile
            target: development
        command: ["sh", "-c", "sleep 100s && npm run dev"]
        ports:
            - 3001:3000
        volumes:
            - ../Authorizatoin:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - ADMIN_USERNAME=username
            - ADMIN_PHONE_NUMBER=phonenumber
            - ADMIN_EMAIL=email
            - ADMIN_PASSWORD=password
            - DB_SUPPORTS_TRANSACTION=true
            - DB_URL=mongodb://main_mongodb_mongos1:27017,main_mongodb_mongos2:27017
            - SESSION_REDIS_TYPE=cluster
            - SESSION_REDIS_INITIAL_NODE_URL=redis://authorization_redis_1:6379
            - REVOKED_TOKENS_REDIS_TYPE=cluster
            - REVOKED_TOKENS_REDIS_INITIAL_NODE_URL=redis://revoked_access_tokens_redis_1:6379
            - MESSAGE_BROKER_TYPE=cluster
            - MESSAGE_BROKER_MANAGEMENT_API_URL=rabbitmq1:15672
            - MESSAGE_BROKER_USERNAME=admin
            - MESSAGE_BROKER_PASSWORD=password
        networks:
            - base
            - authorization
            - authorization_redis

    ############################################################################################# authorization_redis
    authorization_redis_1:
        container_name: authorization_redis_1
        build:
            context: ../Authorizatoin
            dockerfile: ../Authorizatoin/redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=authorization_redis_1
            - REDIS_CLUSTER_INIT=true
            - nodes=authorization_redis_1:6379 authorization_redis_2:6379 authorization_redis_3:6379 authorization_redis_4:6379 authorization_redis_5:6379 authorization_redis_6:6379
        ports:
            - 7000:6379
        networks:
            - authorization_redis

    authorization_redis_2:
        container_name: authorization_redis_2
        build:
            context: ../Authorizatoin
            dockerfile: ../Authorizatoin/redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=authorization_redis_2
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7001:6379
        networks:
            - authorization_redis

    authorization_redis_3:
        container_name: authorization_redis_3
        build:
            context: ../Authorizatoin
            dockerfile: ../Authorizatoin/redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=authorization_redis_3
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7002:6379
        networks:
            - authorization_redis

    authorization_redis_4:
        container_name: authorization_redis_4
        build:
            context: ../Authorizatoin
            dockerfile: ../Authorizatoin/redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=authorization_redis_4
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7003:6379
        networks:
            - authorization_redis

    authorization_redis_5:
        container_name: authorization_redis_5
        build:
            context: ../Authorizatoin
            dockerfile: ../Authorizatoin/redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=authorization_redis_5
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7004:6379
        networks:
            - authorization_redis

    authorization_redis_6:
        container_name: authorization_redis_6
        build:
            context: ../Authorizatoin
            dockerfile: ../Authorizatoin/redis/cluster/Dockerfile
            target: development
        environment:
            - HOSTNAME=authorization_redis_6
            - REDIS_CLUSTER_INIT=false
        ports:
            - 7005:6379
        networks:
            - authorization_redis

networks:
    base:
    main_mongodb:
    revoked_access_tokens_redis:
    rabbitmq_cluster:
    authorization:
    authorization_redis:
    api:
    api_redis:
