version: '3.8'

networks:
    milad_e_commerce_api:
    milad_e_commerce_api_mongodb:
    milad_e_commerce_api_session_redis:
    milad_e_commerce_authorization:
    milad_e_commerce_authorization_mongodb:
    milad_e_commerce_authorization_session_redis:

secrets:
    milad_e_commerce_api_jwt_secret:
        external: true
    milad_e_commerce_api_mongodb_username:
        external: true
    milad_e_commerce_api_mongodb_password:
        external: true
    milad_e_commerce_authorization_jwt_secret:
        external: true
    milad_e_commerce_authorization_mongodb_username:
        external: true
    milad_e_commerce_authorization_mongodb_password:
        external: true
    milad_e_commerce_authorization_access_token_expires_in:
        external: true
    milad_e_commerce_authorization_refresh_token_expires_in:
        external: true
    milad_e_commerce_authorization_otp_provider_username:
        external: true
    milad_e_commerce_authorization_otp_provider_password:
        external: true
    milad_e_commerce_authorization_otp_provider_sender_number:
        external: true
    milad_e_commerce_authorization_email:
        external: true
    milad_e_commerce_authorization_email_password:
        external: true
    milad_e_commerce_authorization_google_client_id:
        external: true
    milad_e_commerce_authorization_google_client_secret:
        external: true

volumes:
    milad_e_commerce_api_mongodb:
    milad_e_commerce_api_session_redis:
    milad_e_commerce_authorization_mongodb:
    milad_e_commerce_authorization_session_redis:

services:
    milad_e_commerce_web:
        image: ghcr.io/hirbod-codes/milad_e_commerce/milad_e_commerce_web:${tag}
        environment:
            VITE_API_URL: http://${server_ip}:1506
            VITE_AUTH_API_URL: http://${server_ip}:1507
            VITE_REDIRECT_URI: http://127.0.0.1:1508/
        ports:
        # Don't forget to change the .env file, if you change the port number ( for google OAuth )
        - 1508:80

    milad_e_commerce_api:
        image: ghcr.io/hirbod-codes/milad_e_commerce/milad_e_commerce_api:${tag}
        ports:
            - 1506:3000
        environment:
            NODE_ENV: production
            HOST: "0.0.0.0"
            PORT: 3000
            DB_DATABASE_NAME: primaryDB
            DB_SUPPORTS_TRANSACTION: "false"
            DB_URL: mongodb://milad_e_commerce_api_mongodb:27017
            REDIS_TYPE: single
            REDIS_INITIAL_NODE_URL: redis://milad_e_commerce_api_session_redis:6379
            secret_prefix: milad_e_commerce_api_
        secrets:
            - milad_e_commerce_api_jwt_secret
            - milad_e_commerce_api_mongodb_username
            - milad_e_commerce_api_mongodb_password
        deploy:
            resources:
                limits:
                    cpus: "0.5"
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 8
        networks:
            - milad_e_commerce_api
            - milad_e_commerce_api_mongodb
            - milad_e_commerce_api_session_redis

    milad_e_commerce_api_mongodb:
        image: ghcr.io/hirbod-codes/milad_e_commerce/milad_e_commerce_api_mongodb_single:${tag}
        environment:
            databaseName: primaryDB
            secret_prefix: milad_e_commerce_api_
        secrets:
            - milad_e_commerce_api_mongodb_username
            - milad_e_commerce_api_mongodb_password
        volumes:
            - milad_e_commerce_api_mongodb:/data/db
        deploy:
            resources:
                limits:
                    cpus: "0.5"
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 8
        networks:
            - milad_e_commerce_api_mongodb

    milad_e_commerce_api_session_redis:
        image: redis:7.0
        environment:
            secret_prefix: milad_e_commerce_api_
        volumes:
            - milad_e_commerce_api_session_redis:/data
        deploy:
            resources:
                limits:
                    cpus: "0.5"
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 8
        networks:
            - milad_e_commerce_api_session_redis

    milad_e_commerce_authorization:
        image: ghcr.io/hirbod-codes/milad_e_commerce/milad_e_commerce_authorization:${tag}
        ports:
            - 1507:3000
        environment:
            NODE_ENV: production
            HOST: "0.0.0.0"
            PORT: 3000
            DB_DATABASE_NAME: primaryDB
            DB_SUPPORTS_TRANSACTION: "false"
            DB_URL: mongodb://milad_e_commerce_authorization_mongodb:27017
            REDIS_TYPE: single
            REDIS_INITIAL_NODE_URL: redis://milad_e_commerce_authorization_session_redis:6379
            secret_prefix: milad_e_commerce_authorization_
        secrets:
            - milad_e_commerce_authorization_jwt_secret
            - milad_e_commerce_authorization_access_token_expires_in
            - milad_e_commerce_authorization_refresh_token_expires_in
            - milad_e_commerce_authorization_otp_provider_username
            - milad_e_commerce_authorization_otp_provider_password
            - milad_e_commerce_authorization_otp_provider_sender_number
            - milad_e_commerce_authorization_email
            - milad_e_commerce_authorization_email_password
            - milad_e_commerce_authorization_google_client_id
            - milad_e_commerce_authorization_google_client_secret
            - milad_e_commerce_authorization_mongodb_username
            - milad_e_commerce_authorization_mongodb_password
        deploy:
            resources:
                limits:
                    cpus: "0.5"
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 8
        networks:
            - milad_e_commerce_authorization
            - milad_e_commerce_authorization_mongodb
            - milad_e_commerce_authorization_session_redis

    milad_e_commerce_authorization_mongodb:
        image: ghcr.io/hirbod-codes/milad_e_commerce/milad_e_commerce_authorization_mongodb_single:${tag}
        environment:
            databaseName: primaryDB
            secret_prefix: milad_e_commerce_authorization_
        secrets:
            - milad_e_commerce_authorization_mongodb_username
            - milad_e_commerce_authorization_mongodb_password
        volumes:
            - milad_e_commerce_authorization_mongodb:/data/db
        deploy:
            resources:
                limits:
                    cpus: "0.5"
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 8
        networks:
            - milad_e_commerce_authorization_mongodb

    milad_e_commerce_authorization_session_redis:
        image: redis:7.0
        environment:
            secret_prefix: milad_e_commerce_authorization_
        volumes:
            - milad_e_commerce_authorization_session_redis:/data
        deploy:
            resources:
                limits:
                    cpus: "0.5"
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 8
        networks:
            - milad_e_commerce_authorization_session_redis