@accessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RlOWUzOTg0ZDQxODFjMmRjODNiOGMiLCJyb2xlIjoiYWRtaW4iLCJ0b2tlbk1vZGUiOiJhY2Nlc3NUb2tlbiIsImlhdCI6MTc0MjY1NDk1MiwiZXhwIjoxNzQyNjU2NzUyLCJpc3MiOiJBdXRob3JpemF0aW9uIFNlcnZlciJ9.BXBHZvVan7Uki4RPeefKa1t8IuO7HGzB4y3kHGr3fP3CEWpcRxnhfHnyq0C3_uxHAy6MSVbdd6ulkPiusJA-pQ
@userId=67de9e3984d4181c2dc83b8c

###
POST http://localhost:3000/orders HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "userId": "{{userId}}",
    "order": {
        "userId": "{{userId}}",
        "products": ["67dec585b7254dd98395228b", "67dec58bb7254dd98395228c"]
    }
}

###
GET http://localhost:3000/orders HTTP/1.1
Accept: application/json

###
PATCH http://localhost:3000/orders HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{userId}}",
    "addViews": 5
}

###
PATCH http://localhost:3000/orders/immutables HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{userId}}",
    "category":{
        "name": "entertainment3"
    }
}

###
DELETE http://localhost:3000/orders HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{userId}}"
}
