@accessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RlOWUzOTg0ZDQxODFjMmRjODNiOGMiLCJyb2xlIjoiYWRtaW4iLCJ0b2tlbk1vZGUiOiJhY2Nlc3NUb2tlbiIsImlhdCI6MTc0MjY3ODgyMSwiZXhwIjoxNzQyNjgwNjIxLCJpc3MiOiJBdXRob3JpemF0aW9uIFNlcnZlciJ9.zic6Ltl3bdrpsFxUgqY-9bZj_z4o-9Gm8mUFH6Qw9iv2qHcI1xcabQAt4aJmU-bDtirS6dqcRzH6l3cSf33geg
@userId=67de9e3984d4181c2dc83b8c
@orderId=67ded49d7c36281c3a01dd26

###
POST http://localhost:3000/orders HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "userId": "{{userId}}",
    "order": {
        "userId": "{{userId}}",
        "products": ["67dec585b7254dd98395228b", "67dec58bb7254dd98395228c"]
    }
}

###
GET http://localhost:3000/orders?userId={{userId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json

###
PATCH http://localhost:3000/orders HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "orderId": "{{orderId}}",
    "order": {
        "address": {
            "text": "aaaaaaaaaaaaaaaaaaaa"
        }
    }
}

###
PATCH http://localhost:3000/orders/immutables HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "orderId": "{{orderId}}",
    "order": {
        "isSent": true
    }
}

###
DELETE http://localhost:3000/orders HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "orderId": "{{orderId}}"
}
