@accessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2U5NWE4ZTM5NjU2NTRhNzIzOTBiZDEiLCJyb2xlIjoiYWRtaW4iLCJ0b2tlbk1vZGUiOiJhY2Nlc3NUb2tlbiIsImlhdCI6MTc0MzQwNzcyOCwiZXhwIjoxNzQzNDA5NTI4LCJpc3MiOiJBdXRob3JpemF0aW9uIFNlcnZlciJ9.VYfd_SMuM_imw0FWpzGz3cqVE0oGpiCwwUwAgbyHARUUIHQ32ApmnA0mM6GPTSw3fXFh0n9ENwFVpuT6joRjUQ
@productId=67ea47a2d557f40102912efc

###
POST http://localhost:3000/products HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "tags": ["tag1", "tag2"],
    "categories": ["category1", "category2"],
    "name": "name6",
    "description": {
        "en": "description1"
    },
    "price": {
        "IRR": 5500000
    },
    "isAvailable": true
}

###
POST http://localhost:3000/products/pictures/{{productId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json
File-Name: testAvatar2
Content-Length: 2048
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="testAvatar2.png"
Content-Type: image/png

< ./testAvatar2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:3000/products/{{productId}} HTTP/1.1
Accept: application/json

###
GET http://localhost:3000/products/pictures/{{productId}} HTTP/1.1
Accept: application/zip

###
GET http://localhost:3000/products HTTP/1.1
Accept: application/json

###
GET http://localhost:3000/products?filter={"$or":[{"name":"name1"},{"name":"name2"}]} HTTP/1.1
Accept: application/json

###
PATCH http://localhost:3000/products HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{productId}}",
    "product": {
        "description": {
            "en": "description2"
        }
    }
}

###
PATCH http://localhost:3000/products/immutables HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{productId}}",
    "product": {
        "views": 15
    }
}

###
DELETE http://localhost:3000/products HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{productId}}"
}
