@accessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RlOWUzOTg0ZDQxODFjMmRjODNiOGMiLCJyb2xlIjoiYWRtaW4iLCJ0b2tlbk1vZGUiOiJhY2Nlc3NUb2tlbiIsImlhdCI6MTc0MjY1MjMyMCwiZXhwIjoxNzQyNjU0MTIwLCJpc3MiOiJBdXRob3JpemF0aW9uIFNlcnZlciJ9.mStngqIzmx6byXNFDu42QOUwELBULBQ7dYvjX7UqwQrg1dErTMf4v_J2KHj6qtDjxi1qDe7DOomLOropNZsNfw
@productId=67deb9ae82aec5fe352caafc

###
POST http://localhost:3000/products HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "tags": ["tag1", "tag2"],
    "categories": ["category1", "category2"],
    "name": "name1",
    "description": {
        "en": "description1"
    },
    "price": {
        "IRR": 5500000
    },
    "isAvailable": true
}

###
GET http://localhost:3000/products/{{productId}} HTTP/1.1
Accept: application/json

###
GET http://localhost:3000/products HTTP/1.1
Accept: application/json

###
PATCH http://localhost:3000/products HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{productId}}",
    "product": {
        "description": {
            "en": "description2"
        }
    }
}

###
PATCH http://localhost:3000/products/immutables HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{productId}}",
    "product": {
        "views": 15
    }
}

###
DELETE http://localhost:3000/products HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "{{productId}}"
}
