version: '3.8'

services:
    # to test nginx configuration
    # web:
    #     container_name: web
    #     build:
    #         context: ../../frontend/web/
    #         dockerfile: Dockerfile.development
    #         target: development
    #     ports:
    #       # Don't forget to change the .env file, if you change the port number ( for google OAuth )
    #       - 5173:80
    #     networks:
    #         - web

    authorization:
        container_name: authorization
        build: 
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - 3001:3000
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - REDIS_TYPE=single
            - REDIS_INITIAL_NODE_URL=redis://authorization_session_redis:6379
            - DB_SUPPORTS_TRANSACTION=false
            - DB_URL=mongodb://authorization_mongodb:27017
        networks:
            - authorization
            - base

    authorization_mongodb:
        container_name: authorization_mongodb
        build:
            context: .
            dockerfile: ./mongodb/single/Dockerfile
            target: development
        ports:
                - 8083:27017
        environment:
            MONGODB_USERNAME: admin
            MONGODB_PASSWORD: password
            databaseName: primaryDB
        networks:
            - authorization

    authorization_session_redis:
        container_name: authorization_session_redis
        image: redis:7.0
        ports:
            - 6379:6379
        networks:
            - authorization

    # authorization_revoked_tokens_redis:
    #     container_name: authorization_revoked_tokens_redis
    #     image: redis:7.0
    #     ports:
    #         - 6379:6379
    #     networks:
    #         - authorization

networks:
    web:
    base:
    api:
    authorization:
