version: '3.8'

services:
    ############################################################################################# main_mongodb
    main_mongodb:
        container_name: main_mongodb
        build:
            context: .
            dockerfile: ./mongodb/single/Dockerfile
            target: development
        ports:
                - 8083:27017
        environment:
            MONGODB_USERNAME: admin
            MONGODB_PASSWORD: password
            databaseName: primaryDB
        networks:
            - base

    ############################################################################################# authorization
    authorization:
        container_name: authorization
        build: 
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - 3001:3000
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - DB_SUPPORTS_TRANSACTION=false
            - DB_URL=mongodb://main_mongodb:27017
            - REDIS_TYPE=single
            - REDIS_INITIAL_NODE_URL=redis://authorization_redis:6379
        networks:
            - authorization

    ############################################################################################# authorization_redis
    authorization_redis:
        container_name: authorization_redis
        image: redis:7.0
        ports:
            - 6379:6379
        networks:
            - authorization_redis

networks:
    authorization:
