server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/ngonx/ssl/localhost.crt;
    ssl_certificate_key /etc/ngonx/ssl/localhost.key;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html =404;
    }

    location /auth/ {
        proxy_pass http://authorization:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded_Proto $scheme;

        proxy_pass_header *;

        proxy_cookie_domain authorization localhost;
        proxy_cookie_path / /;
    }

    location /api/ {
        proxy_pass http://api:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded_Proto $scheme;

        proxy_pass_header *;
    }

    # Handle 404 errors
    error_page 404 /index.html;

    # Enable gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}

server {
    listen 80;
    server_name localhost *.localhost;
    
    # Redirect all HTTP requests to HTTPS
    return 301 https://$host$request_uri;
}
