@accessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RkZWVhMmNiMTE3Y2Q0YmYyOGNmYTIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDI2MDMwMjQsImV4cCI6MTc0MjYwNDgyNCwiaXNzIjoiQXV0aG9yaXphdGlvbiBTZXJ2ZXIifQ.I7NrGDk_iajXiQDzEck3FQl_TnWdbzUmuTUhi2whgq4s-5xNM6Kc5GRKW0R_FRSvlphIMn3c3EyJE3E39vzGcA

###
POST http://localhost:3001/roles HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "name": "test5",
    "displayName":{
        "fa": "تست5"
    },
    "privileges": ["67dbeb5eec4dfacd4c911f98"]
}

###
GET http://localhost:3001/roles HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json

###
PATCH http://localhost:3001/roles HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "67dd0f7c11586bf8cf9b7199",
    "role": {
        "privileges": ["67dbeb5eec4dfacd4c911f97"]
    }
}

###
DELETE http://localhost:3001/roles HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "67dd1204e681fa66dd321c38"
}

###
PATCH http://localhost:3001/roles/assign HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "userId": "67ddeea2cb117cd4bf28cfa2",
    "role": "default"
}
