@accessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RkMmMzM2Y5Y2Y2ZTEzN2E2YWRkZTMiLCJyb2xlIjoiZGVmYXVsdCIsImlhdCI6MTc0MjU2ODE4NywiZXhwIjoxNzQyNTY5OTg3LCJpc3MiOiJBdXRob3JpemF0aW9uIFNlcnZlciJ9.2qV30tZ8AiFEnJKI4R1i5sBMfD-f5tov32Gh4c1ktuZL_kxaeyD-YC_jaIL8mku5BV7_WNNUkaJqZEP5GudoJQ

###
GET http://localhost:3001/user HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json

###
GET http://localhost:3001/user/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/octet-stream

###
POST http://localhost:3001/user/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json
File-Name: testAvatar
Content-Length: 2048
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="testAvatar.png"
Content-Type: image/png

< ./testAvatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
Delete http://localhost:3001/user/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/octet-stream

###
PATCH http://localhost:3001/user HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "lastName": "aaa"
}

###
DELETE http://localhost:3001/user HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "67dd1204e681fa66dd321c38"
}

###
PATCH http://localhost:3001/user/assign HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "userId": "67dbfaf73d3d544326014d98",
    "role": "test4"
}
