@accessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RiZmFmNzNkM2Q1NDQzMjYwMTRkOTgiLCJyb2xlIjoiZGVmYXVsdCIsImlhdCI6MTc0MjU0NjAzNCwiZXhwIjoxNzQyNTQ3ODM0LCJpc3MiOiJBdXRob3JpemF0aW9uIFNlcnZlciJ9.cwwpUATk6ASVKP2bHCulaf0osXRuBsMnAZFNeW1gFaULtbNNOGhqloxjVJaVlHZgLtQ7JWcCPjjZxOuAkaYZ1w

###
GET http://localhost:3001/user HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json

###
GET http://localhost:3001/user/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json

###
POST http://localhost:3001/user/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json
File-Name: testAvatar
Content-Length: 2048
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./testAvatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

{
    "firstName": "aaa"
}

###
PATCH http://localhost:3001/user HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "firstName": "aaa"
}

###
DELETE http://localhost:3001/user HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "id": "67dd1204e681fa66dd321c38"
}

###
PATCH http://localhost:3001/user/assign HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
    "userId": "67dbfaf73d3d544326014d98",
    "role": "test4"
}
