###
POST http://localhost:3001/auth/email/send-code HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "example@domain.com"
}

###
POST http://localhost:3001/auth/email/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "example@domain.com",
    "password": "Pass99%aa",
    "code": 900877
}

###
POST http://localhost:3001/auth/email/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "example@domain.com",
    "password": "Pass99%aa"
}
