###
POST http://localhost:3001/auth/tokens/retrieve-access-token HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "refreshToken": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RiZmFmNzNkM2Q1NDQzMjYwMTRkOTgiLCJyb2xlIjoiZGVmYXVsdCIsImlhdCI6MTc0MjQ3MDk3NCwiZXhwIjoxNzQzMDc1Nzc0LCJpc3MiOiJBdXRob3JpemF0aW9uIFNlcnZlciJ9.GbojEd8uP6SfO_Bwd2eMce4cwplv7lRzWiGhUAENEs_CH2RcfIoHUMI-sHNN2Hi_sSnpjLmQK3p37LsQBOOvnw",
    "userId": "67dbfaf73d3d544326014d98"
}
