upstream mongos_servers {
    server authorization_mongodb_mongos1:27017;
    server authorization_mongodb_mongos2:27017;
}

server {
    listen 27017;
    location / {
        proxy_pass http://mongos_servers;
    }
}
